print('this is main')
print('fix bug')
print('main commit 1')
print('main commit 2')
print('main commit 3')

print('dev commit 1')
print('dev commit 2')
print('main commit 4')
print('main commit 4')
print('main commit 5')
